import mongoose from "mongoose";

// const studentProfileSchema = new mongoose.Schema({});

// export const studentProfileModel = mongoose.model("studentProfile", studentProfileSchema);

// defaultValues: {
//     interested: "Yes",
//     fullName: "",
//     enrollment: "",
//     university: "",
//     course: "MCA",
//     yoa: "",
//     yop: "",
//     dob: "",
//     gender: "Male",
//     category: "General",
//     speciallyAbled: "Yes",
//     ssc: "",
//     hssc: "",
//     diplomaPercentage: "",
//     aggregateUGCGPA: "",
//     aggregateUGPercentage: "",
//     aggregatePGCGPA: "",
//     aggregatePGPercentage: "",
//     UGCourse: "",
//     UGSpecialization: "",
//     UGyop: "",
//     activeBacklog: "No",
//     numberOfBacklog: 0,
//     backlogHistory: "No",
//     diplomaInAnyCourse: "",
//     diplomayop: "",
//     diplomayoa: "",
//     diplomaInstitute: "",
//     mobileNo: "",
//     altMobileNo: "",
//     email: "",
//     sscSchoolName: "",
//     sscBoard: "",
//     sscyop: "",
//     hsscSchoolName: "",
//     hsscBoard: "",
//     hsscyop: "",
//     gapInStudies: "No",
//     noOfGap: 0,
//     ISemSGPA: "",
//     ISemATKT: 0,
//     IISemSGPA: "",
//     IISemATKT: 0,
//     IIISemSGPA: "",
//     IIISemATKT: 0,
//     IVSemSGPA: "",
//     IVSemATKT: 0,
//     VSemSGPA: "",
//     VSemATKT: 0,
//     VISemSGPA: "",
//     VISemATKT: 0,
//     VIISemSGPA: "",
//     VIISemATKT: 0,
//     VIIISemSGPA: "",
//     VIIISemATKT: 0,
//     currentSem: "",
//     localAddress: "",
//     localPincode: "",
//     permanentAddress: "",
//     hometown: "",
//     state: "",
//     permanentPincode: "",
//     fatherName: "",
//     fatherContactNo: "",
//     fatherOccupation: "",
//     motherName: "",
//     motherContactNo: "",
//     exp: "",
//     image: "",
//     resume: "",
//     affirmation: ""
// }
// const mongoose = require("mongoose");

const studentProfileSchema = new mongoose.Schema(
	{
		userId: { type: String, required: true }, // id generated by mongodb white registering the student for login
		// Personal Information
		name: { type: String, required: true },
		enrollmentNumber: { type: String, required: true, unique: true },
		dob: { type: String, required: true }, // Date of Birth (DD/MM/YY)
		gender: { type: String, required: true },
		category: { type: String, required: true },
		speciallyAbled: { type: String, required: true },
		mobileNo: { type: String, required: true },
		altMobileNo: { type: String },
		email: { type: String, required: true, unique: true },
		localAddress: { type: String, required: true },
		localPincode: { type: String, required: true },
		permanentAddress: { type: String, required: true },
		permanentPincode: { type: String, required: true },
		hometown: { type: String, required: true },
		state: { type: String, required: true },
		passportPhoto: { type: String }, // URL or base64 encoded image
		// Academic Information
		ssc: {
			percentage: { type: Number, required: true },
			schoolName: { type: String, required: true },
			board: { type: String, required: true },
			yearOfPassing: { type: Number, required: true },
		},
		hssc: {
			percentage: { type: Number },
			schoolName: { type: String },
			board: { type: String },
			yearOfPassing: { type: Number },
		},
		diploma: {
			percentage: { type: Number, default: "" },
			admissionYear: { type: Number, default: "" },
			passOutYear: { type: Number, default: "" },
			instituteName: { type: String, default: "" },
		},
		undergraduate: {
			universityName: { type: String },
			course: { type: String },
			aggregateCGPA: { type: Number },
			aggregatePercentage: { type: Number },
			specialization: { type: String },
			yearOfAdmission: { type: Number },
			yearOfPassing: { type: Number },
		},
		postgraduate: {
			universityName: { type: String },
			course: { type: String },
			yearOfAdmission: { type: Number },
			yearOfPassing: { type: Number },
			aggregateCGPA: { type: Number },
			aggregatePercentage: { type: Number },
		},
		semesterDetails: [
			{
				semester: { type: Number, required: true },
				sgpa: { type: Number },
				atkt: { type: Number }, // Number of ATKT in the semester
			},
		],

		// Academic Gaps and Backlogs
		gaps: {
			hasGap: { type: String, required: true },
			numberOfYears: { type: Number },
		},
		backlogs: {
			hasActiveBacklogs: { type: String, required: true },
			totalActiveBacklogs: { type: Number },
			backlogHistory: { type: String, required: true },
		},

		// Family Details
		father: {
			name: { type: String, required: true },
			contactNo: { type: String, required: true },
			occupation: { type: String },
		},
		mother: {
			name: { type: String, required: true },
			contactNo: { type: String, required: true },
		},

		// Career and Experience
		internship: { type: String }, // Company name or details of the internship
	},
	{ timestamps: true }
);

export const studentProfileModel = mongoose.model("StudentProfile", studentProfileSchema);
